#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
vpath %.c ../..
unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/syslink/utils/rtos/bios6
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/utils.js:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/utils.js
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/xdc.tci:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/xdc.tci
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/template.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/template.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/om2.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/om2.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/xmlgen.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/xmlgen.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/xmlgen2.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/xmlgen2.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/Warnings.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/Warnings.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/IPackage.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/IPackage.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/package.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/package.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/services/global/Clock.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/services/global/Clock.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/services/global/Trace.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/services/global/Trace.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/bld.js:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/bld.js
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/BuildEnvironment.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/PackageContents.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/PackageContents.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/_gen.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/_gen.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Library.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Library.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Executable.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Executable.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Repository.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Repository.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Configuration.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Configuration.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Script.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Script.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Manifest.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Manifest.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Utils.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/Utils.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/ITarget.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/ITarget.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/ITarget2.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/ITarget2.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/ITarget3.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/ITarget3.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/ITargetFilter.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/ITargetFilter.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/package.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/xdc/bld/package.xs
/opt/Project/Camera/Source/ti_tools/syslink_2_21_02_10/packages/_config.bld:
package.mak: /opt/Project/Camera/Source/ti_tools/syslink_2_21_02_10/packages/_config.bld
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/ITarget.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/ITarget.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/C28_large.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/C28_large.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/C28_float.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/C28_float.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/package.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/package.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/elf/ITarget.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/elf/ITarget.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/elf/package.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/elf/package.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/arm/elf/IArm.xs
/opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/arm/elf/package.xs:
package.mak: /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/arm/elf/package.xs
package.mak: package.bld
endif

ti.targets.elf.C674.rootDir ?= /opt/Project/Camera/Source/ipnc_rdk/../ti_tools/cgt6x_7_4_6
ti.targets.elf.packageBase ?= /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/elf/
ti.targets.arm.elf.M3.rootDir ?= /opt/Project/Camera/Source/ipnc_rdk/../ti_tools/cgt470_5_1_3
ti.targets.arm.elf.packageBase ?= /opt/Project/Camera/Source/ti_tools/xdctools_3_25_05_94/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674

.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.syslink.utils.rtos.bios6.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.syslink.utils.rtos.bios6" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/rel/undefinedti/syslink/utils/rtos/bios6package/package.rel.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.syslink.utils.rtos.bios6 $@

.libraries,e674 .libraries: lib/debug/ti.syslink.utils.rtos.bios6.ae674

-include lib/debug/ti.syslink.utils.rtos.bios6.ae674.mak
lib/debug/ti.syslink.utils.rtos.bios6.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Trace.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Cfg.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Trace.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Cfg.oe674 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.oe674 
lib/debug/ti.syslink.utils.rtos.bios6.ae674: export C_DIR=
lib/debug/ti.syslink.utils.rtos.bios6.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/debug/ti.syslink.utils.rtos.bios6.ae674
.libraries,e674 .libraries: lib/release/ti.syslink.utils.rtos.bios6.ae674

-include lib/release/ti.syslink.utils.rtos.bios6.ae674.mak
lib/release/ti.syslink.utils.rtos.bios6.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Trace.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Cfg.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Trace.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Cfg.oe674 package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.oe674 
lib/release/ti.syslink.utils.rtos.bios6.ae674: export C_DIR=
lib/release/ti.syslink.utils.rtos.bios6.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/release/ti.syslink.utils.rtos.bios6.ae674
.libraries,em3 .libraries: lib/debug/ti.syslink.utils.rtos.bios6.aem3

-include lib/debug/ti.syslink.utils.rtos.bios6.aem3.mak
lib/debug/ti.syslink.utils.rtos.bios6.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Trace.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Cfg.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armar  rq $@   package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Trace.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Cfg.oem3 package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.oem3 
lib/debug/ti.syslink.utils.rtos.bios6.aem3: export C_DIR=
lib/debug/ti.syslink.utils.rtos.bios6.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/debug/ti.syslink.utils.rtos.bios6.aem3
.libraries,em3 .libraries: lib/release/ti.syslink.utils.rtos.bios6.aem3

-include lib/release/ti.syslink.utils.rtos.bios6.aem3.mak
lib/release/ti.syslink.utils.rtos.bios6.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Trace.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Cfg.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armar  rq $@   package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Trace.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Cfg.oem3 package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.oem3 
lib/release/ti.syslink.utils.rtos.bios6.aem3: export C_DIR=
lib/release/ti.syslink.utils.rtos.bios6.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/release/ti.syslink.utils.rtos.bios6.aem3
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.syslink.utils.rtos.bios6.oe674,copy
package_ti.syslink.utils.rtos.bios6.oe674,copy : package_ti.syslink.utils.rtos.bios6.oe674,0,copy package_ti.syslink.utils.rtos.bios6.oe674,1,copy 
	@

package_ti.syslink.utils.rtos.bios6.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674
package_ti.syslink.utils.rtos.bios6.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oe674
.PHONY: package_ti.syslink.utils.rtos.bios6.se674,copy
package_ti.syslink.utils.rtos.bios6.se674,copy : package_ti.syslink.utils.rtos.bios6.se674,0,copy package_ti.syslink.utils.rtos.bios6.se674,1,copy 
	@

package_ti.syslink.utils.rtos.bios6.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.se674
package_ti.syslink.utils.rtos.bios6.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.se674
.PHONY: OsalPrint.oe674,copy
OsalPrint.oe674,copy : OsalPrint.oe674,0,copy OsalPrint.oe674,1,copy 
	@

OsalPrint.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oe674
OsalPrint.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oe674
.PHONY: OsalPrint.se674,copy
OsalPrint.se674,copy : OsalPrint.se674,0,copy OsalPrint.se674,1,copy 
	@

OsalPrint.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.se674
OsalPrint.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.se674
.PHONY: OsalKfile.oe674,copy
OsalKfile.oe674,copy : OsalKfile.oe674,0,copy OsalKfile.oe674,1,copy 
	@

OsalKfile.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oe674
OsalKfile.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oe674
.PHONY: OsalKfile.se674,copy
OsalKfile.se674,copy : OsalKfile.se674,0,copy OsalKfile.se674,1,copy 
	@

OsalKfile.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.se674
OsalKfile.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.se674
.PHONY: MemoryOS.oe674,copy
MemoryOS.oe674,copy : MemoryOS.oe674,0,copy MemoryOS.oe674,1,copy 
	@

MemoryOS.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oe674
MemoryOS.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oe674
.PHONY: MemoryOS.se674,copy
MemoryOS.se674,copy : MemoryOS.se674,0,copy MemoryOS.se674,1,copy 
	@

MemoryOS.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.se674
MemoryOS.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.se674
.PHONY: Trace.oe674,copy
Trace.oe674,copy : Trace.oe674,0,copy Trace.oe674,1,copy 
	@

Trace.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Trace.oe674
Trace.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Trace.oe674
.PHONY: Trace.se674,copy
Trace.se674,copy : Trace.se674,0,copy Trace.se674,1,copy 
	@

Trace.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Trace.se674
Trace.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Trace.se674
.PHONY: Cfg.oe674,copy
Cfg.oe674,copy : Cfg.oe674,0,copy Cfg.oe674,1,copy 
	@

Cfg.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Cfg.oe674
Cfg.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Cfg.oe674
.PHONY: Cfg.se674,copy
Cfg.se674,copy : Cfg.se674,0,copy Cfg.se674,1,copy 
	@

Cfg.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Cfg.se674
Cfg.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Cfg.se674
.PHONY: TraceDrv.oe674,copy
TraceDrv.oe674,copy : TraceDrv.oe674,0,copy TraceDrv.oe674,1,copy 
	@

TraceDrv.oe674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.oe674
TraceDrv.oe674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.oe674
.PHONY: TraceDrv.se674,copy
TraceDrv.se674,copy : TraceDrv.se674,0,copy TraceDrv.se674,1,copy 
	@

TraceDrv.se674,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.se674
TraceDrv.se674,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.se674
.PHONY: package_ti.syslink.utils.rtos.bios6.oem3,copy
package_ti.syslink.utils.rtos.bios6.oem3,copy : package_ti.syslink.utils.rtos.bios6.oem3,0,copy package_ti.syslink.utils.rtos.bios6.oem3,1,copy 
	@

package_ti.syslink.utils.rtos.bios6.oem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oem3
package_ti.syslink.utils.rtos.bios6.oem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.oem3
.PHONY: package_ti.syslink.utils.rtos.bios6.sem3,copy
package_ti.syslink.utils.rtos.bios6.sem3,copy : package_ti.syslink.utils.rtos.bios6.sem3,0,copy package_ti.syslink.utils.rtos.bios6.sem3,1,copy 
	@

package_ti.syslink.utils.rtos.bios6.sem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.sem3
package_ti.syslink.utils.rtos.bios6.sem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/package/package_ti.syslink.utils.rtos.bios6.sem3
.PHONY: OsalPrint.oem3,copy
OsalPrint.oem3,copy : OsalPrint.oem3,0,copy OsalPrint.oem3,1,copy 
	@

OsalPrint.oem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oem3
OsalPrint.oem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.oem3
.PHONY: OsalPrint.sem3,copy
OsalPrint.sem3,copy : OsalPrint.sem3,0,copy OsalPrint.sem3,1,copy 
	@

OsalPrint.sem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.sem3
OsalPrint.sem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalPrint.sem3
.PHONY: OsalKfile.oem3,copy
OsalKfile.oem3,copy : OsalKfile.oem3,0,copy OsalKfile.oem3,1,copy 
	@

OsalKfile.oem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oem3
OsalKfile.oem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.oem3
.PHONY: OsalKfile.sem3,copy
OsalKfile.sem3,copy : OsalKfile.sem3,0,copy OsalKfile.sem3,1,copy 
	@

OsalKfile.sem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.sem3
OsalKfile.sem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/OsalKfile.sem3
.PHONY: MemoryOS.oem3,copy
MemoryOS.oem3,copy : MemoryOS.oem3,0,copy MemoryOS.oem3,1,copy 
	@

MemoryOS.oem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oem3
MemoryOS.oem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.oem3
.PHONY: MemoryOS.sem3,copy
MemoryOS.sem3,copy : MemoryOS.sem3,0,copy MemoryOS.sem3,1,copy 
	@

MemoryOS.sem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.sem3
MemoryOS.sem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6/MemoryOS.sem3
.PHONY: Trace.oem3,copy
Trace.oem3,copy : Trace.oem3,0,copy Trace.oem3,1,copy 
	@

Trace.oem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Trace.oem3
Trace.oem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Trace.oem3
.PHONY: Trace.sem3,copy
Trace.sem3,copy : Trace.sem3,0,copy Trace.sem3,1,copy 
	@

Trace.sem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Trace.sem3
Trace.sem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Trace.sem3
.PHONY: Cfg.oem3,copy
Cfg.oem3,copy : Cfg.oem3,0,copy Cfg.oem3,1,copy 
	@

Cfg.oem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Cfg.oem3
Cfg.oem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Cfg.oem3
.PHONY: Cfg.sem3,copy
Cfg.sem3,copy : Cfg.sem3,0,copy Cfg.sem3,1,copy 
	@

Cfg.sem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common/Cfg.sem3
Cfg.sem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/common/Cfg.sem3
.PHONY: TraceDrv.oem3,copy
TraceDrv.oem3,copy : TraceDrv.oem3,0,copy TraceDrv.oem3,1,copy 
	@

TraceDrv.oem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.oem3
TraceDrv.oem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.oem3
.PHONY: TraceDrv.sem3,copy
TraceDrv.sem3,copy : TraceDrv.sem3,0,copy TraceDrv.sem3,1,copy 
	@

TraceDrv.sem3,0,copy : package/lib/lib/debug/ti.syslink.utils.rtos.bios6/TraceDrv.sem3
TraceDrv.sem3,1,copy : package/lib/lib/release/ti.syslink.utils.rtos.bios6/TraceDrv.sem3

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_syslink_utils_rtos_bios6
ti_syslink_utils_rtos_bios6.tar: package/package.bld.xml
ti_syslink_utils_rtos_bios6.tar: package/build.cfg
ti_syslink_utils_rtos_bios6.tar: package/package.xdc.inc
ti_syslink_utils_rtos_bios6.tar: package/package.cfg.xdc.inc
ti_syslink_utils_rtos_bios6.tar: lib/debug/ti.syslink.utils.rtos.bios6.ae674
ti_syslink_utils_rtos_bios6.tar: lib/release/ti.syslink.utils.rtos.bios6.ae674
ti_syslink_utils_rtos_bios6.tar: lib/debug/ti.syslink.utils.rtos.bios6.aem3
ti_syslink_utils_rtos_bios6.tar: lib/release/ti.syslink.utils.rtos.bios6.aem3
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_syslink_utils_rtos_bios6.tar.dep
endif
package/rel/ti_syslink_utils_rtos_bios6/ti/syslink/utils/rtos/bios6/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_syslink_utils_rtos_bios6.tar: package/rel/ti_syslink_utils_rtos_bios6.xdc.inc package/rel/ti_syslink_utils_rtos_bios6/ti/syslink/utils/rtos/bios6/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_syslink_utils_rtos_bios6.xdc.inc,package/rel/ti_syslink_utils_rtos_bios6.tar.dep)


release release,ti_syslink_utils_rtos_bios6: all ti_syslink_utils_rtos_bios6.tar
clean:: .clean
	-$(RM) ti_syslink_utils_rtos_bios6.tar
	-$(RM) package/rel/ti_syslink_utils_rtos_bios6.xdc.inc
	-$(RM) package/rel/ti_syslink_utils_rtos_bios6.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard lib/debug))
    $(shell $(MKDIR) lib/debug)
endif
ifeq (,$(wildcard lib/release))
    $(shell $(MKDIR) lib/release)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/debug))
    $(shell $(MKDIR) package/lib/lib/debug)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/package)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/rtos/osal/bios6)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.utils.rtos.bios6/common)
endif
ifeq (,$(wildcard package/lib/lib/release))
    $(shell $(MKDIR) package/lib/lib/release)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/package))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/package)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/rtos/osal/bios6)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.utils.rtos.bios6/common))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.utils.rtos.bios6/common)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.syslink.utils.rtos.bios6.pjt
